### ISSUE TITLE
Wrong type for Config in ProjectSettingsModel

### ISSUE THREAD

**Issue by rosieks** [pulumi/pulumi-dotnet#366]
### What happened?

There is wrong property type for `Config` in `ProjectSettingsModel`. Right now it's [string](https://github.com/pulumi/pulumi-dotnet/blob/main/sdk/Pulumi.Automation/Serialization/ProjectSettingsModel.cs#L24) while specfication assumets it's [map](https://www.pulumi.com/docs/iac/concepts/projects/project-file/#config-options).
That cause than when I try to use LocalWorkspace automation it crash on deserialization.
```
(Line: 5, Col: 3, Idx: 82) - (Line: 5, Col: 3, Idx: 82): Exception during deserialization
```

### Example

Code that crashes:

```csharp
var args = new LocalProgramArgs($"new-stack", pathToProject);
var stack = await LocalWorkspace.CreateOrSelectStackAsync(args);
```

Configuration *Pulumi.yaml*:
```yaml
name: MyProject
runtime: dotnet
description: Persistence
config: 
  pulumi-disable-default-providers:
  - kubernetes
  some-setting: dev
```

### Output of `pulumi about`

I'm using NuGet package Pulumi.Automation Version="3.67.1"

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
